// Minimal GitHub REST client for opening an auto-fix pull request.
//
// Uses undici fetch directly (no octokit dependency). The pure helpers
// (branch name, PR body) are unit-tested; the network flow is a thin, linear
// sequence of documented REST calls: read base ref → create branch → write each
// file → open PR. Throws a descriptive error on any non-2xx so the caller can
// surface it to the user.
import { fetch as uFetch } from "undici";
import type { FileChange, RemediationPlan } from "./remediation";

const API = "https://api.github.com";
const UA = "SEOPlatform-AutoFix";

export interface PrTarget {
  token: string;
  owner: string;
  repo: string;
  baseBranch?: string; // defaults to the repo's default branch
}

export interface OpenedPr {
  url: string;
  number: number;
  branch: string;
}

// Deterministic, filesystem-safe branch name derived from a seed (e.g. crawlId).
export function prBranchName(seed: string): string {
  const slug = seed.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 32) || "audit";
  return `seo-autofix/${slug}`;
}

// Human-readable PR description from the remediation plan.
export function composePrBody(plan: RemediationPlan, meta: { domain: string; healthNote?: string }): string {
  const lines: string[] = [
    `Automated SEO fixes for **${meta.domain}** generated from the latest site audit.`,
    "",
  ];
  if (plan.files.length) {
    lines.push("### Files changed");
    for (const f of plan.files) lines.push(`- \`${f.path}\` (${f.action}) — fixes \`${f.reason}\``);
    lines.push("");
  }
  if (plan.manual.length) {
    lines.push("### Needs a manual/template change");
    for (const m of plan.manual) lines.push(`- \`${m.code}\` — ${m.note}`);
    lines.push("");
  }
  lines.push("---", "_Generated by the SEO platform auto-fix. Review before merging._");
  return lines.join("\n");
}

async function gh<T>(target: PrTarget, method: string, path: string, body?: unknown): Promise<T> {
  const res = await uFetch(`${API}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${target.token}`,
      Accept: "application/vnd.github+json",
      "User-Agent": UA,
      "X-GitHub-Api-Version": "2022-11-28",
      ...(body ? { "Content-Type": "application/json" } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
    signal: AbortSignal.timeout(20000),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`GitHub ${method} ${path} → ${res.status}: ${text.slice(0, 200)}`);
  }
  return (await res.json()) as T;
}

// Validate the token has access to the repo and return its default branch.
// Throws (via gh) on a bad token / missing repo, so connect fails loudly.
export async function verifyRepoAccess(target: PrTarget): Promise<{ defaultBranch: string; permissionPush: boolean }> {
  const r = await gh<{ default_branch: string; permissions?: { push?: boolean } }>(
    target,
    "GET",
    `/repos/${target.owner}/${target.repo}`,
  );
  return { defaultBranch: r.default_branch, permissionPush: r.permissions?.push ?? false };
}

const b64 = (s: string) => Buffer.from(s, "utf8").toString("base64");

// Write one file onto a branch via the Contents API (create, or update/append
// if it already exists on the base).
async function writeFile(target: PrTarget, branch: string, file: FileChange): Promise<void> {
  const path = file.path.replace(/^\/+/, "");
  let sha: string | undefined;
  let existing = "";
  try {
    const cur = await gh<{ sha: string; content: string }>(
      target,
      "GET",
      `/repos/${target.owner}/${target.repo}/contents/${encodeURIComponent(path)}?ref=${branch}`,
    );
    sha = cur.sha;
    existing = Buffer.from(cur.content, "base64").toString("utf8");
  } catch {
    /* file doesn't exist yet — a plain create */
  }
  const content = file.action === "append" && existing ? existing + file.content : file.content;
  // Already up-to-date — skip the PUT so re-running doesn't create noise commits.
  if (existing === content) return;
  await gh(target, "PUT", `/repos/${target.owner}/${target.repo}/contents/${encodeURIComponent(path)}`, {
    message: `SEO auto-fix: ${file.reason}`,
    content: b64(content),
    branch,
    ...(sha ? { sha } : {}),
  });
}

// Full flow: create a branch off base, write every file, open the PR.
export async function openPullRequest(
  target: PrTarget,
  branch: string,
  title: string,
  body: string,
  files: FileChange[],
): Promise<OpenedPr> {
  // Resolve the base branch (default branch if not given) and its head SHA.
  const base =
    target.baseBranch ||
    (await gh<{ default_branch: string }>(target, "GET", `/repos/${target.owner}/${target.repo}`)).default_branch;
  const baseRef = await gh<{ object: { sha: string } }>(
    target,
    "GET",
    `/repos/${target.owner}/${target.repo}/git/ref/heads/${base}`,
  );

  // Create the working branch (ignore "already exists" so retries are safe).
  try {
    await gh(target, "POST", `/repos/${target.owner}/${target.repo}/git/refs`, {
      ref: `refs/heads/${branch}`,
      sha: baseRef.object.sha,
    });
  } catch (e) {
    if (!String(e).includes("422")) throw e;
  }

  for (const file of files) await writeFile(target, branch, file);

  // If a PR from this branch is already open, return it instead of erroring on a
  // duplicate — makes "Create PR" safe to click more than once.
  const existing = await gh<{ html_url: string; number: number }[]>(
    target,
    "GET",
    `/repos/${target.owner}/${target.repo}/pulls?head=${target.owner}:${branch}&state=open`,
  );
  if (existing.length) return { url: existing[0].html_url, number: existing[0].number, branch };

  const pr = await gh<{ html_url: string; number: number }>(
    target,
    "POST",
    `/repos/${target.owner}/${target.repo}/pulls`,
    { title, head: branch, base, body },
  );
  return { url: pr.html_url, number: pr.number, branch };
}
